import { z } from 'zod';

// Define reusable schemas

// Shop validation schema
export const shopSchema = z.object({
  username: z.string().min(3, 'Username must be at least 3 characters').max(30, 'Username must be less than 30 characters'),
  password: z.string().min(6, 'Password must be at least 6 characters').max(100, 'Password must be less than 100 characters'),
  name: z.string().min(1, 'Shop name is required').max(100, 'Shop name must be less than 100 characters'),
  contactPerson: z.string().min(1, 'Contact person is required').max(50, 'Contact person must be less than 50 characters'),
  contactPhone: z.string().min(1, 'Contact phone is required').max(20, 'Contact phone must be less than 20 characters'),
  city: z.string().min(1, 'City is required').max(50, 'City must be less than 50 characters'),
  exactLocation: z.string().min(1, 'Exact location is required').max(200, 'Exact location must be less than 200 characters'),
  tradeLicenseNumber: z.string().max(50, 'Trade license number must be less than 50 characters').optional().nullable(),
  tinNumber: z.string().max(50, 'TIN number must be less than 50 characters').optional().nullable(),
  discount: z.number().min(0, 'Discount must be a non-negative number').max(100, 'Discount must be less than or equal to 100'),
  monthlySalesTarget: z.number().min(0, 'Monthly sales target must be a non-negative number').optional().nullable(), // Make it optional and nullable
  status: z.enum(['Active', 'Inactive', 'Pending']).optional(),
  // New fields for variant visibility control
  showVariantDetails: z.boolean().optional(),
  maxVisibleVariants: z.number().min(1).max(1000).optional(),
  // New field for Telegram integration
  telegram_channel_id: z.string().max(50, 'Telegram channel ID must be less than 50 characters').optional().nullable()
  // Removed aiDistributionMode field
});

// Product variant validation schema
export const productVariantSchema = z.object({
  id: z.string().min(1, 'Variant ID is required'),
  productId: z.string().min(1, 'Product ID is required'),
  color: z.string().min(1, 'Color is required').max(50, 'Color must be less than 50 characters'),
  size: z.string().min(1, 'Size is required').max(20, 'Size must be less than 20 characters'),
  stock: z.number().int().nonnegative('Stock must be a positive number'),
  imageUrl: z.string().refine(val => {
    if (!val) return true;
    try {
      new URL(val);
      return true;
    } catch {
      return val.startsWith('/');
    }
  }, 'Image URL must be a valid URL or a relative path starting with /').optional().nullable(),
});

// Product variant schema for creation (without id and productId)
export const productVariantCreateSchema = z.object({
  color: z.string().min(1, 'Color is required').max(50, 'Color must be less than 50 characters'),
  size: z.string().min(1, 'Size is required').max(20, 'Size must be less than 20 characters'),
  stock: z.number().int().nonnegative('Stock must be a positive number'),
  imageUrl: z.string().refine(val => {
    if (!val) return true;
    try {
      new URL(val);
      return true;
    } catch {
      return val.startsWith('/');
    }
  }, 'Image URL must be a valid URL or a relative path starting with /').optional().nullable(),
});

// Age pricing validation schema
export const agePricingSchema = z.object({
  id: z.number().optional(), // Optional since it's auto-generated by the database
  productId: z.string().min(1, 'Product ID is required'),
  ageMin: z.number().int().min(0, 'Minimum age must be a non-negative integer').optional(),
  ageMax: z.number().int().min(0, 'Maximum age must be a non-negative integer').optional(),
  price: z.number().positive('Price must be a positive number'),
  cost: z.number().min(0, 'Cost must be a non-negative number').optional(),
  sizes: z.string().max(100, 'Sizes must be less than 100 characters').optional().nullable(),
});

// Product validation schema
export const productSchema = z.object({
  id: z.string().optional(),
  productCode: z.string().max(50, 'Product code must be less than 50 characters').optional(),
  name: z.string().max(100, 'Product name must be less than 100 characters').optional(),
  category: z.string().max(50, 'Category must be less than 50 characters').optional(),
  price: z.number().positive('Price must be a positive number').optional(),
  cost: z.number().min(0, 'Cost must be a non-negative number').optional(),
  minimumStockLevel: z.number().int().nonnegative('Minimum stock level must be a non-negative integer').optional(),
  variants: z.array(z.any()).optional(), // Make variants optional for partial updates
  agePricing: z.array(agePricingSchema).optional(),
  imageUrl: z.string().refine(val => {
    if (!val) return true;
    try {
      new URL(val);
      return true;
    } catch {
      return val.startsWith('/');
    }
  }, 'Image URL must be a valid URL or a relative path starting with /').optional().nullable(),
  description: z.string().max(500, 'Description must be less than 500 characters').optional().nullable(),
  readyToDeliver: z.number().min(0).max(1).optional(), // 0 or 1
  created_at: z.string().optional(),
  
  // Advanced Production Fields
  piecesPerSet: z.number().min(1).optional(),
  sampleDevelopmentStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleQuotationStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleSizeSetStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleSizeSetQCStatus: z.enum(['Pending', 'Passed', 'Failed']).optional(),
  sampleCounterStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleCounterQCStatus: z.enum(['Pending', 'Passed', 'Failed']).optional(),
  sampleApprovedBy: z.string().optional().nullable(),
  sampleApprovedDate: z.string().optional().nullable(),
});

// Product schema for creation
export const productCreateSchema = z.object({
  id: z.string().optional(),
  productCode: z.string().min(1, 'Product code is required').max(50, 'Product code must be less than 50 characters'),
  name: z.string().min(1, 'Product name is required').max(100, 'Product name must be less than 100 characters'),
  category: z.string().min(1, 'Category is required').max(50, 'Category must be less than 50 characters'),
  price: z.number().positive('Price must be a positive number'),
  cost: z.number().min(0, 'Cost must be a non-negative number').optional(),
  minimumStockLevel: z.number().int().nonnegative('Minimum stock level must be a non-negative integer'),
  variants: z.array(productVariantCreateSchema).min(1, 'At least one variant is required'),
  agePricing: z.array(agePricingSchema).optional(),
  imageUrl: z.string().refine(val => {
    if (!val) return true;
    try {
      new URL(val);
      return true;
    } catch {
      return val.startsWith('/');
    }
  }, 'Image URL must be a valid URL or a relative path starting with /').optional().nullable(),
  description: z.string().max(500, 'Description must be less than 500 characters').optional().nullable(),
  readyToDeliver: z.number().min(0).max(1).optional(), // 0 or 1
  created_at: z.string().optional(),
  
  // Advanced Production Fields
  piecesPerSet: z.number().min(1).optional(),
  sampleDevelopmentStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleQuotationStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleSizeSetStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleSizeSetQCStatus: z.enum(['Pending', 'Passed', 'Failed']).optional(),
  sampleCounterStatus: z.enum(['Pending', 'In Progress', 'Completed']).optional(),
  sampleCounterQCStatus: z.enum(['Pending', 'Passed', 'Failed']).optional(),
  sampleApprovedBy: z.string().optional().nullable(),
  sampleApprovedDate: z.string().optional().nullable(),
});

// Order validation schema
export const orderSchema = z.object({
  shopId: z.string().min(1, 'Shop ID is required'),
  shopName: z.string().min(1, 'Shop name is required').max(100, 'Shop name must be less than 100 characters'),
  date: z.string().min(1, 'Date is required'),
  status: z.enum(['Pending', 'Confirmed', 'Processing', 'Shipped', 'Delivered', 'Cancelled']),
  amount: z.number().positive('Amount must be a positive number'),
  items: z.string().min(1, 'Items are required'),
  paymentSlipUrl: z.string().max(200, 'Payment slip URL must be less than 200 characters').optional().nullable(),
  dispatchInfo: z.string().max(200, 'Dispatch info must be less than 200 characters').optional().nullable(),
  deliveryDate: z.string().max(20, 'Delivery date must be less than 20 characters').optional().nullable(),
  isClosed: z.number().min(0).max(1, 'Is closed must be 0 or 1').optional(),
  feedback: z.string().max(500, 'Feedback must be less than 500 characters').optional().nullable(),
});

// Marketing order validation schema
export const marketingOrderSchema = z.object({
  orderNumber: z.string().min(1, 'Order number is required').max(50, 'Order number must be less than 50 characters'),
  productName: z.string().min(1, 'Product name is required').max(100, 'Product name must be less than 100 characters'),
  productCode: z.string().min(1, 'Product code is required').max(50, 'Product code must be less than 50 characters').regex(/^[A-Z]{2}(-[A-Z]{2})?-\d{3,}([/-]\d{2,})?$/i, "Code must follow format: XX-XXX, XX-XXX/XX, XX-XXXX, or XX-XX-XXX/XX"),
  description: z.string().max(500, 'Description must be less than 500 characters').optional().nullable(),
  quantity: z.number().positive('Quantity must be a positive number'),
  status: z.enum(['Placed Order', 'Planning', 'Sample Making', 'Cutting', 'Sewing', 'Finishing', 'Quality Inspection', 'Packing', 'Delivery', 'Completed', 'Cancelled']).optional(),
  cuttingStatus: z.string().max(50, 'Cutting status must be less than 50 characters').optional().nullable(),
  sewingStatus: z.string().max(50, 'Sewing status must be less than 50 characters').optional().nullable(),
  finishingStatus: z.string().max(50, 'Finishing status must be less than 50 characters').optional().nullable(),
  qualityInspectionStatus: z.string().max(50, 'Quality inspection status must be less than 50 characters').optional().nullable(),
  packingStatus: z.string().max(50, 'Packing status must be less than 50 characters').optional().nullable(),
  deliveryStatus: z.string().max(50, 'Delivery status must be less than 50 characters').optional().nullable(),
  assignedTo: z.string().optional().nullable(),
  cuttingCompletionDate: z.string().max(20, 'Cutting completion date must be less than 20 characters').optional().nullable(),
  sewingCompletionDate: z.string().max(20, 'Sewing completion date must be less than 20 characters').optional().nullable(),
  finishingCompletionDate: z.string().max(20, 'Finishing completion date must be less than 20 characters').optional().nullable(),
  qualityInspectionCompletionDate: z.string().max(20, 'Quality inspection completion date must be less than 20 characters').optional().nullable(),
  packingCompletionDate: z.string().max(20, 'Packing completion date must be less than 20 characters').optional().nullable(),
  deliveryCompletionDate: z.string().max(20, 'Delivery completion date must be less than 20 characters').optional().nullable(),
  sizeSetSampleApproved: z.string().max(50, 'Size set sample approved must be less than 50 characters').optional().nullable(),
  productionStartDate: z.string().max(20, 'Production start date must be less than 20 characters').optional().nullable(),
  productionFinishedDate: z.string().max(20, 'Production finished date must be less than 20 characters').optional().nullable(),
  
  // Gatekeeper and Sequencing
  isPlanningApproved: z.boolean().optional(),
  priority: z.number().optional(),
  
  // Attachments
  ppmMeetingAttached: z.string().optional().nullable(),
  sampleApprovalAttached: z.string().optional().nullable(),
  cuttingQualityAttached: z.string().optional().nullable(),
});

// User validation schema
export const userSchema = z.object({
  username: z.string().min(3, 'Username must be at least 3 characters').max(30, 'Username must be less than 30 characters'),
  password: z.string().min(6, 'Password must be at least 6 characters').max(100, 'Password must be less than 100 characters'),
  role: z.enum(['factory', 'shop', 'store', 'finance', 'planning', 'sample_maker', 'cutting', 'sewing', 'finishing', 'packing', 'quality_inspection', 'marketing']),
});

// Notification validation schema
export const notificationSchema = z.object({
  userType: z.enum(['factory', 'shop', 'store', 'finance', 'planning', 'sample_maker', 'cutting', 'sewing', 'finishing', 'packing', 'quality_inspection', 'designer', 'marketing']),
  shopId: z.string().max(50, 'Shop ID must be less than 50 characters').optional().nullable(),
  title: z.string().min(1, 'Title is required').max(100, 'Title must be less than 100 characters'),
  description: z.string().min(1, 'Description is required').max(500, 'Description must be less than 500 characters'),
  href: z.string().min(1, 'Href is required').max(200, 'Href must be less than 200 characters'),
  isRead: z.number().min(0).max(1, 'Is read must be 0 or 1').optional(),
});

// Helper function to sanitize strings (remove potentially dangerous characters)
export function sanitizeString(str: string): string {
  if (!str) return str;
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;');
    // Removed / replacement as it breaks URLs and file paths
}

// Helper function to sanitize input data
export function sanitizeInput(data: any): any {
  if (data === null || data === undefined) return data;
  
  if (typeof data === 'string') {
    return sanitizeString(data);
  }
  
  if (Array.isArray(data)) {
    return data.map(item => sanitizeInput(item));
  }
  
  if (typeof data === 'object') {
    const sanitized: any = {};
    for (const [key, value] of Object.entries(data)) {
      sanitized[key] = sanitizeInput(value);
    }
    return sanitized;
  }
  
  return data;
}